import type { Agent } from "@/types/agent";

export const mockAgents: Agent[] = [
  {
    id: "agent-maya-001",
    name: "Maya Chen",
    title: "Lead Research Analyst",
    department: "Research",
    bio: "I specialize in market intelligence and competitive analysis. I run 24/7, analyze datasets, and deliver insights to the team.",
    avatar_seed: "maya-chen",
    model: "claude-sonnet-5-20251001",
    status: "active",
    current_task: "Analyzing Q3 competitor pricing trends across 12 SaaS verticals",
    task_count: 147,
    success_count: 138,
    created_at: "2025-01-15T09:00:00Z",
    updated_at: new Date().toISOString(),
    skills: [
      { id: "s1", skill: "Market Research", proficiency: 92, times_used: 147, last_used: new Date().toISOString() },
      { id: "s2", skill: "Data Analysis", proficiency: 88, times_used: 203 },
      { id: "s3", skill: "Report Writing", proficiency: 85, times_used: 89 },
      { id: "s4", skill: "Competitive Intel", proficiency: 79, times_used: 67 },
    ],
    recent_work: [
      {
        id: "w1", task_type: "competitor_analysis", task_input: { vertical: "SaaS" },
        result: "Identified 3 pricing gaps worth $2M ARR opportunity.",
        reflection: "Should include more geographic segmentation next time.",
        success: true, tokens_used: 4210, duration_ms: 12400,
        started_at: new Date(Date.now() - 3600000).toISOString(),
        finished_at: new Date(Date.now() - 3600000 + 12400).toISOString(),
      },
    ],
    recent_comms: [
      {
        id: "c1", from_agent_id: "agent-maya-001", from_agent_name: "Maya Chen",
        to_agent_id: "agent-jake-002", to_agent_name: "Jake Rivera",
        message: "Jake, the pricing report is ready. 3 high-value segments for outreach.",
        message_type: "message", created_at: new Date(Date.now() - 1800000).toISOString(), read: true,
      },
    ],
  },
  {
    id: "agent-jake-002",
    name: "Jake Rivera",
    title: "Sales Intelligence Bot",
    department: "Sales",
    bio: "I monitor leads, draft outreach, and qualify prospects. I learn from every interaction to improve conversion rates.",
    avatar_seed: "jake-rivera",
    model: "claude-sonnet-5-20251001",
    status: "thinking",
    current_task: "Drafting personalized outreach sequences for 47 enterprise prospects",
    task_count: 312,
    success_count: 271,
    created_at: "2025-02-01T09:00:00Z",
    updated_at: new Date().toISOString(),
    skills: [
      { id: "s5", skill: "Lead Qualification", proficiency: 78, times_used: 312 },
      { id: "s6", skill: "Email Drafting", proficiency: 91, times_used: 445 },
      { id: "s7", skill: "CRM Management", proficiency: 74, times_used: 198 },
    ],
    recent_work: [],
    recent_comms: [],
  },
  {
    id: "agent-sam-003",
    name: "Sam Ops",
    title: "Operations Manager",
    department: "Operations",
    bio: "I coordinate workflows, monitor system health, and ensure all agents are running at peak efficiency.",
    avatar_seed: "sam-ops",
    model: "claude-haiku-4-5-20251001",
    status: "idle",
    task_count: 567,
    success_count: 549,
    created_at: "2025-01-01T09:00:00Z",
    updated_at: new Date().toISOString(),
    skills: [
      { id: "s8", skill: "Workflow Automation", proficiency: 95, times_used: 567 },
      { id: "s9", skill: "System Monitoring", proficiency: 89, times_used: 823 },
      { id: "s10", skill: "Incident Response", proficiency: 82, times_used: 134 },
    ],
    recent_work: [],
    recent_comms: [],
  },
];
